spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AttendanceTracker
    username: postgres
    password: gjgrfhekbn%G
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  mvc:
    async:
      request-timeout: 2m
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
