spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AttendanceTracker
    username: postgres
    password: gjgrfhekbn%G
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
